name: ${DOCKER_PROD_NAME}

services:
  express:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 5000
      FRONTEND_URL: ${FRONTEND_URL}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '${DOCKER_PROD_EXPRESS_PORT}:5000'
    volumes:
      - express_uploads:/app/uploads
    init: true
    restart: unless-stopped

volumes:
  express_uploads: